### ISSUE TITLE
enable bubbletea unit tests to run in github actions

### ISSUE THREAD

**Issue by plastikfan** [snivilised/pixa#169]
To avoid the "could not open a new TTY" error when a tests runs in ci, the github actions config needs a change.

Issue might be related to [gh-actions 241](https://github.com/actions/runner/issues/241)

**Comment by plastikfan** [comment]
As suggested by perplexity, I tried this in tthe workflow:

```yaml
      - name: Set terminal environment
        run: export TERM=xterm
```

... and in context:

```yaml
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set terminal environment
        run: export TERM=xterm
```
