### ISSUE TITLE
define commands and options

### ISSUE THREAD

**Issue by plastikfan** [snivilised/pixa#2]
Include options definitions with appropriate cobrass validators.

Should not implement the functionality, that will be done under a different issue (#3)

To allow pixa to delete options to magick, the user would invoke using --. Any options provided after --, are not interpreted by cobra, this is a posix standard. See this [cobra issue](https://github.com/spf13/cobra/issues/739) for more info

**Comment by plastikfan** [comment]
Finally managed to find the fix for the bogus pre-commit type check errors, just use this in pre commit config:

```yml
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.52.2
    hooks:
      - id: golangci-lint
```

Also:
- install golangci-lint from binary [see Binaries](https://golangci-lint.run/usage/install/#local-installation)
- in ci workflows, dont use @latest for golanci-lint, pin a specific version, current latest is 1.52.2
