### ISSUE TITLE
rename magick package to proxy

### ISSUE THREAD

**Issue by plastikfan** [snivilised/pixa#46]
this reflects the fact that pixa should not be tied to magick. Theoretically, we should be able to use another application, so the domain package should be something generic.

**Comment by plastikfan** [comment]
also change the golangci-lint timeout in this update

___.golangci-lint:___

```yaml
run:
  issues-exit-code: 1
  timeout: 5m
```
